### PR TITLE
Fix typo and markdown issues

### PR DESCRIPTION
**Pull request by rodolfobandeira**

### CODE REVIEW

**Comment by mkudelya** [comment]
Hi @rodolfobandeira 

Would you please sign our Contributor License Agreement? (https://www.orocrm.com/contributor-license-agreement) Thank you!

**Comment by rodolfobandeira** [comment]
Hi @mkudelya

Already did this last year for other OroCRM projects. Anyways, I just signed again. 
Thank you

**Comment by mkudelya** [comment]
Hi @rodolfobandeira 

Your PR has been merged. Changes from PR will be synced to the public repository in a few days. Thank you.

**Comment by rodolfobandeira** [comment]
Cleaning up some old pending PRs under my username. Since this is sitting here for a while, closing it.
Thanks!

**Pull request closed without merging**
